obj-$(CONFIG_LUSTREFSX_FS) += fid/
obj-$(CONFIG_LUSTREFSX_FS) += obdclass/
obj-$(CONFIG_LUSTREFSX_FS) += ptlrpc/
obj-$(CONFIG_LUSTREFSX_FS) += obdecho/
obj-$(CONFIG_LUSTREFSX_FS) += mgc/
obj-$(CONFIG_LUSTREFSX_FS) += lov/ osc/ mdc/ lmv/ llite/ fld/

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
