obj-$(CONFIG_LUSTREFSX_FS)	+= mdc.o

mdc-y		:= mdc_request.o mdc_reint.o lproc_mdc.o mdc_lib.o mdc_locks.o
mdc-y		+= mdc_changelog.o mdc_dev.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
