obj-$(CONFIG_LUSTREFSX_LNET)        += fld.o

ccflags-y	+= -I$(srctree)/drivers/staging/lustrefsx/include

fld-y		:= fld_request.o fld_cache.o lproc_fld.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules

