obj-$(CONFIG_LUSTREFSX_FS)	+= osc.o

osc-y := osc_request.o lproc_osc.o osc_dev.o osc_object.o osc_page.o
osc-y += osc_lock.o osc_io.o osc_quota.o osc_cache.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
