obj-$(CONFIG_LUSTREFSX_LNET)	+= ksocklnd.o

ksocklnd-y		:= socklnd.o socklnd_cb.o socklnd_lib.o
ksocklnd-y		+= socklnd_modparams.o socklnd_proto.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
