obj-$(CONFIG_LUSTREFSX_FS)	+= lov.o

lov-y	:= lov_dev.o lov_ea.o lov_io.o lov_lock.o lov_merge.o lov_obd.o
lov-y	+= lov_object.o lov_offset.o lov_pack.o lov_page.o lov_pool.o
lov-y	+= lov_request.o lovsub_dev.o lovsub_object.o
lov-y	+= lproc_lov.o

include $(srctree)/drivers/staging/lustrefsx/Makefile.rules
